### ISSUE TITLE
After upgrade to 0.115 shortcuts gives error

### ISSUE THREAD

**Issue by TheRealLouCipher** [kalkih/mini-media-player#414]
After upgrade to 0.115 shortcuts now gives an error. Worked as expected on 0.114.4. Running supported supervised install.

````2020-09-18 10:23:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140602360781072] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 490, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/squeezebox/media_player.py", line 483, in async_play_media
    content = json.loads(media_id)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kalkih** [comment]
This is most likely related to the service call you're doing from the shortcut and not the actual shortcut feature by itself.
What does the shortcut configuration look like?
Check the Home Assistant release notes and see if anything related to `play_media` and/or the squeezebox component has changed.

**Comment by TheRealLouCipher** [comment]
````
                shortcuts:
                  columns: 5
                  hide_when_off: false
                  buttons:
                    - image: /local/images/rixfm.jpg
                      type: playlist
                      id: http://fm01-ice.stream.khz.se/fm01_mp3
...

**Comment by kalkih** [comment]
Thanks, will look into it.

**Comment by TheRealLouCipher** [comment]
Changing
````type: playlist````
to
````type: music````
and the shortcuts work again.

So I guess it is related to the breaking change for Squeezebox in 0.115 https://github.com/home-assistant/core/pull/38214

**Comment by kalkih** [comment]
Great, thanks for sharing!
