### ISSUE TITLE
Can no longer select a radio station using the buttons in the card (Squeezebox)

### ISSUE THREAD

**Issue by verstrepeng** [kalkih/mini-media-player#440]
This config has been working for months, and now no longer working since a few weeks, I don't know which update caused the issue.
Config:
```          - type: "custom:mini-media-player"
            entity: media_player.keuken
            icon: mdi:music-box-outline
            toggle_power: false
            info: scroll
            more_info: false
            max_volume: 40
            volume_stateless: true
            #replace_mute: play_pause
            hide:
              power_state: false
              progress: true
              controls: false
              icon: true
              mute: true
              volume_level: false
            shortcuts:
              hide_when_off: false
              columns: 4
              buttons:
                - name: StuBru
                  type: playlist
                  id: 'http://opml.radiotime.com/Tune.ashx?id=s6503&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085'
                - name: Q Music
                  type: playlist
                  id: 'http://opml.radiotime.com/Tune.ashx?id=s69243&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085'
                - name: Joe
                  type: playlist
                  id: 'http://opml.radiotime.com/Tune.ashx?id=s102123&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085'
                - name: MNM Hits
                  type: playlist
                  id: 'http://opml.radiotime.com/Tune.ashx?id=s69137&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085'
```

Error:
```Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/squeezebox/media_player.py", line 501, in async_play_media
    content = json.loads(media_id)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
It seems more people reportes this issue on the HA forums.

**Comment by gbollas** [comment]
Same issue here. Used to work fine but now the playlist is not accessible.

**Comment by verstrepeng** [comment]
I got it solved.
You should replace type: playlist by type: music, for me that did the trick…

**Comment by gbollas** [comment]
Worked! thanks!
