### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by Kobiash** [kalkih/mini-media-player#469]
============= ytube_music_player Integration Error ================
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 143, in check_api
    self._api = ytmusicapi.YTMusic(self._header_file)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

**Comment by kalkih** [comment]
Hello,
This issue is related to [ytube_music_player](https://github.com/KoljaWindeler/ytube_music_player) and not this card.
I suggest you open an issue over there.
