### ISSUE TITLE
Entity media_player.denon_home does not support this service.

### ISSUE THREAD

**Issue by TPochobradsky** [kalkih/mini-media-player#714]
Hello, thank you for nice Lovelace card. I would like to use it with my Denon home 150 (using two in stereo pair). Unfortunately it doesn't work. Thank you for help.

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:655
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:14:31 (1 occurrences)
Last logged: 09:14:31

[140049333373776] Entity media_player.denon_home_150 does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 655, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.denon_home_150 does not support this service.

**Comment by BartGysens** [comment]
Having the same issue.
When I try to stop/start music, change volume, ... from the Spotify-card I get an error: **Entity media_player.spotify_account does not support this service.**

I'm playing on an iPad connected to my stereo (wired).

- Home Assistant 2023.1.4
- Supervisor 2022.12.1
- Operating System 9.4
- Frontend-versie: 20230110.0 - latest
- Spotify-account = free account
- Latest version of Spotify and Mini Media Player plugins (installed 14/01/2023)

'''Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:655
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:31:08 (4 occurrences)
Last logged: 12:52:29

[140142962117504] Entity media_player.spotify_account does not support this service.
[140143229843488] Entity media_player.spotify_account does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 655, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.spotify_account does not support this service.'''
