### ISSUE TITLE
Shortcut buttons not working

### ISSUE THREAD

**Issue by arsaboo** [kalkih/mini-media-player#94]
So, I added the following to my config:
```yaml
      - type: custom:mini-media-player
        entity: media_player.shieldtv
        artwork: cover
        hide:
          volume: true
        shortcuts:
          columns: 4
          buttons:
            - icon: mdi:kodi
              type: script
              id: script.shieldtv_kodi
            - icon: mdi:plex
              type: script
              id: script.shieldtv_plex
            - icon: mdi:youtube
              type: script
              id: script.shieldtv_youtube
            - icon: mdi:netflix
              type: script
              id: script.shieldtv_netflix
```
Here's how it appears, which seems incorrect as I was hoping them all to be in one row:
![image](https://user-images.githubusercontent.com/18319734/53899619-9aa60b80-4008-11e9-9e25-497751dd4873.png)

Also, clicking one of the buttons gives the following error:
```bash
Log Details (ERROR)
Wed Mar 06 2019 11:57:23 GMT-0500 (Eastern Standard Time)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 278, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 294, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 581, in play_media
    raise NotImplementedError()
NotImplementedError
```
The scripts work fine when I run them using services, so that is not an issue.

**Comment by iantrich** [comment]
Drop “script.” From each “id “

**Comment by arsaboo** [comment]
still the same. Also, docs indicate using `script.`

**Comment by iantrich** [comment]
Yeah, I know. Was just trying to eliminate possibilities without looking at any code :)

**Comment by arsaboo** [comment]
Is it something to do with custom_component. Here are the [component files](https://github.com/arsaboo/homeassistant-config/tree/master/custom_components/androidtv).

**Comment by kalkih** [comment]
Make sure you got the latest version of the card, seems like you are running an older version prior to script was supported as type.

If you got the latest version make sure the cache has cleared properly.

**Comment by kalkih** [comment]
> Here's how it appears, which seems incorrect as I was hoping them all to be in one row:

They should be, if you are on the latest version

**Comment by arsaboo** [comment]
Ok...deleted everything and added it back. It is working now :+1:
